- .travis.yml
- ci/travis-ci.sh
[Variables in the .travis.yml](http://docs.travis-ci.com/user/environment-variables/#Variables-in-the-.travis.yml)
> Move environmental variables to .travis.yml

- .travis.yml
- Gruntfile.js
- ci/ssh-config
- ci/travis-ci.sh
- package.json
Reverts kalamuna/kalastatic#39
> Revert "Allow deploying from Grunt"

- package.json
- src/about.md
- src/cool-things.md
- src/index.md
- src/styles/layouts/_header.scss
- templates/partials/header-fixednav.html
Yup.
Most of the heavy lifting is a new version of metalsmith-swig-helpers  and templates/partials/header-fixednav.html
> Nav Highlighting

- .npmrc
- package.json
> let node modules co-exist with Drupal

- templates/html.html
a bit more robust handling of page body tag slug  (class on body tag)
> tweaks to page slugs

- package.json
@soniktrooth this creates a ```{{varName|limit}}``` filter
> updates metalsmith-swig-helpers

- package.json
update to 0.7.0 so we can build the thing
> Updating metalsmith sass version

- src/navigation.yaml
Without this there's a whole feature of the project kinda hidden.
> Adding styleguide to main nav

- src/styles/base/_bsvars.scss
> Bringing back the contrast to style guide nav

- .travis.yml
- Gruntfile.js
This fixes some of the Pantheon deployment variables.
> Fix Pull Request deployment variables

- src/styles/base/_bootstrap_custom.scss
> Add some of the Bootstrap styles

- templates/partials/news-teaser.html
> Make news teasers actual teasers

- src/config.yaml
- src/styles/layouts/_footer.scss
- templates/partials/footer.html
> Footer license info

- bower.json
- metalsmith.json
- package.json
- src/contact.md
- src/js/contact.js
- src/js/global.js
- src/js/kala_utils.js
- templates/contact.html
This simplifies the use of the contact form.
> Use the xor-crypt swig filter

- metalsmith.json
- src/carousel.md
- src/collections/examples/carousel.md
- src/examples.md
- src/navigation.yaml
- templates/examples.html
Adding an examples page that displays examples via a collection. Yes I am a clever girl.
> Examples section

- src/index.md
- src/styles/base/_mixins.scss
- src/styles/layouts/_homepage.scss
- templates/home.html
https://github.com/kalamuna/kalastatic/issues/30 Now with 100% more glitch.
> Add Homepage Content

- src/styles/_fontawesome.scss
> Update Font Awesome KSS

- bower.json
- src/styles/base/_bootstrap_custom.scss
> Fix for Bootstrap SASS breadcrumb break

- src/styles/main.scss
- src/styles/organisms/_footer.scss
> Clean up the headings for the styleguide

- Gruntfile.js
- package.json
> Move around config

- src/components/organisms/nav_fixed_top/nav_fixed_top.html
- src/components/organisms/nav_kalastatic/nav_kalastatic.html
- src/config/navigation.metadata
- src/content/team/andrew.md
- src/content/team/josh.md
- src/content/team/rob.md
- src/content/team/thiago.md
- src/styles/_fontawesome.scss
This is to help KS live inside and outside of Drupal as per #202
> Fixing relative paths

- src/components/molecules/lede/lede.html
- src/content/about.md
> Fix the Hi Hello on About page

- package.json
> Fix metalsmith-sass to use native

- metalsmith.json
Small tweak to turn on sourcemapping
> Adds sourcemapping

- kss-node.json
- package.json
- src/config/navigation.metadata
Updated some things in kss-bootstrap.
#237
> #237: KSS Bootstrap path

- Gruntfile.js
- package.json
https://github.com/kalamuna/kalastatic/issues/61
> Add BrowserSync

- metalsmith.json
- package.json
- templates/layouts/html.html
- templates/pages/home.html
> metalsmith-kalastatic-dot-module

- README.md
- pa11y.json
- package.json
https://github.com/kalamuna/kalastatic/issues/104
http://pa11y-kalastatic.at.kalamuna.com/a11y/index.html
> Add Accessibility HTML report

- templates/layouts/html.html
https://github.com/kalamuna/kalastatic/issues/269 Was missing the crucial ingredient.
:+1:
> KSTAT-269 Fix basePath

- package.json
#260 0 Brings in a few things:
- Added List styleguides
- Added more Typography styleguides
- Added Tooltip styleguide
- Added ScrollSpy styleguide
- Added Button state styleguides
- Fixed file permissions on CSS files
- Fix homepage link to current web root
- Fix weight of styleguides
- Fix lead body copy to be a sub-heading of body copy
> KSTAT-260 Update kss-bootstrap

- .travis.yml
- README.md
- bin/kalastatic-pa11y.js
- pa11y.json
- package.json
https://kalamuna.atlassian.net/browse/EECS-200
> EECS-200 Allow a11y on multiple pages

- README.md
Add documentation for development tasks. #279
Read through https://github.com/kalamuna/kalastatic/blob/kstat-279/README.md#tasks
> KSTAT-279 Add Task docs

- package.json
re #296
cc @madeofpeople @soniktrooth @andrewmallis
> Temporary fix from issue caused by node-sass 3.5.x

- src/components/atoms/content_placeholder/_content_placeholder.scss
- src/components/layouts/layout_1/_layout_1.scss
- src/components/layouts/layout_2/_layout_2.scss
- src/content/layouts/layout_1.md
- src/content/layouts/layout_2.md
- src/styles/main.scss
- templates/pages/layouts/layout_1.html
- templates/pages/layouts/layout_2.html
> Feature/josh/301  layouts

- CHANGELOG
- README.md
- package.json
#288 
Uses https://www.npmjs.com/package/build-changelog to automate building the changelog.
> KSTAT-288 Add a CHANGELOG

- CHANGELOG.md
https://github.com/kalamuna/kalastatic/blob/a67148304f64c3097b2288826aaeea123c35bda2/CHANGELOG.md
> KSTAT-288 Add CHANGELOG.md

- .sass-lint.yml
- Gruntfile.js
- package.json
- src/components/organisms/nav_fixed_top/_nav_fixed_top.scss
- src/components/organisms/nav_kalastatic/_nav_kalastatic.scss
> Adding extreme sass linting radness

- src/components/atoms/button/_button.scss
- src/components/atoms/content_placeholder/_content_placeholder.scss
- src/components/layouts/layout_1/_layout_1.scss
- src/components/molecules/bootstrap_carousel_item/_bootstrap_carousel_item.scss
- src/components/molecules/bootstrap_carousel_nav/_bootstrap_carousel_nav.scss
- src/components/molecules/breadcrumb/_breadcrumb.scss
- src/components/molecules/cta/_cta.scss
- src/components/molecules/header_search/_header_search.scss
- src/components/molecules/lede/_lede.scss
- src/components/molecules/listing/_listing.scss
- src/components/molecules/modal/_modal.scss
- src/components/organisms/footer/_footer.scss
- src/components/organisms/nav_fixed_top/_nav_fixed_top.scss
- src/components/organisms/nav_kalastatic/_nav_kalastatic.scss
- src/components/organisms/nav_kalastatic/nav_kalastatic.html
- src/content/examples/bootstrap_carousel.md
- src/styles/_fontawesome.scss
- src/styles/base/_bootstrap_custom.scss
- src/styles/base/_bsvars.scss
- src/styles/base/_extendables.scss
- src/styles/base/_mixins.scss
- src/styles/base/_typography.scss
- src/styles/kalastatic.scss
- src/styles/main.scss
- src/styles/pages/_bootstrap_carousel_example.scss
- src/styles/pages/_homepage.scss
- src/styles/pages/_team.scss
@soniktrooth this reduces the number of sass warnings to 15, and the number of errors to 0
> fixing sass lint issues

- src/content/examples/bootstrap-carousel-example.md
- src/styles/pages/_bootstrap_carousel_example.scss
> fix bootstrap carousel example

- README.md
> KSTAT-352 Add kalastatic.yml documentation

- README.md
https://github.com/kalamuna/kalastatic/issues/324
Recommend use of npm scripts.
> KSTAT-324 Update npm script documentation

- README.md
- bin/kalastatic
- src/kalastatic.js
- test/fixtures/start/expected/index.html
- test/fixtures/start/index-redirect.html
- test/fixtures/start/kalastatic.yaml
This is for https://github.com/kalamuna/progenity.com/pull/187
> PROGMI-215 Add more BrowserSync options

- docs/404.md
- docs/approach.md
- docs/browsersync.md
- docs/cache.md
- docs/collections.md
- docs/components.md
- docs/config.md
- docs/contributing.md
- docs/deployment.md
- docs/dir-structure.md
- docs/drupal.md
- docs/ecosystem.md
- docs/filters.md
- docs/fragment-id.md
- docs/gobal-vars.md
- docs/javascript.md
- docs/kalatheme.md
- docs/new-page.md
- docs/objectives-2.md
- docs/testbed.md
- docs/testing.md
- docs/troubleshooting.md
- docs/twig.md
> KSTAT-399 Bring in old docs

- docs/6-Development.md
- docs/index.md
> KSTAT-403 Semantic Versioning

- docs/2-Components.md
> Start on components section

- docs/1-Conventions.md
A first pass at documenting the outcomes of 
https://github.com/kalamuna/kalastatic/issues/393
and
https://kalamuna.atlassian.net/browse/PROGMI-175
@soniktrooth  let me know if im using the right base branch.
> Docus two point oh  conventions

- docs/4-Prototyping.md
> KSTAT-441 Add initial prototyping section

- docs/index.md
first pass at something that says what Kalastatic is
> #434 add basic intro section

- docs/5-Integrations.md
> KSTAT-432 Add Deployment section

- docs/6-Development.md
> KSTAT-436 Add Development docs

- docs/1-Getting-Started.md
- docs/2-Components.md
- docs/3-Styleguide.md
- docs/5-Integrations.md
- docs/index.md
Cleans up some of the stubs, the headings, and adapts the 1-Conventions section to Getting Started.
> Headings and Getting Started

- docs/5-Integrations.md
http://kalastatic.readthedocs.io/en/latest/5-Integrations/#deployment
was showing
> fix code formatting

- docs/index.md
First crack at at 'features' list. Tried to group things a little and throw in some 'buzz' words so the cool kids think we're one of the cool kids.
> #435: Adding features list to front page docs

- docs/2-Components.md
- docs/index.md
We should not misspell words like education.
> documentation updates

- docs/3-Styleguide.md
- docs/5-Integrations.md
> more documentation updates

- docs/5-Integrations.md
https://github.com/kalamuna/kalastatic/issues/491
> KSTAT-491 Add dump() section about debugging

- docs/7-Resources.md
#489 https://trello.com/c/819PRrUV/18-create-a-wiki-page-for-twig-resources-and-learning
> Add a Resources page

- docs/5-Integrations.md
> Remove Components relative link

- docs/2-Components.md
https://github.com/kalamuna/kalastatic/blob/cc-docs/docs/2-Components.md#create-component
> Update kalastatic cc command docs

- docs/2-Components.md
> fixing code layout in docs

- docs/index.md
4 spaces ended up doing the trick
> Better indenting on docs lists

- bin/kalastatic
> browsersync: Disable opening the window

- README.md
> Whoopsies. Missing some quotes.

- .travis.yml
> Travis: Test Node.js 11

- src/kalastatic.js
- test/libraries/sampleJavaScript.js
- test/package.json
- test/source_files/index.html.twig
https://kalamuna.atlassian.net/browse/KSTAT-172
> KSTAT-172: Better error handling for attach_library()

- src/kalastatic.js
https://kalamuna.atlassian.net/browse/KSTAT-173
> KSTAT-173: Error handling for namespaces

- src/kalastatic.js
- test/package.json
- test/source_files/index.html.twig
https://kalamuna.atlassian.net/browse/KSTAT-174
> KSTAT-174: Rename the script/stylesheet definition names

- examples/simple/pages/index.html.twig
- package.json
- src/kalastatic.js
https://kalamuna.atlassian.net/browse/KSTAT-178
> KSTAT-178: Add Markdown support

- examples/simple/package.json
- src/kalastatic.js
https://kalamuna.atlassian.net/browse/KSTAT-184
> KSTAT-184: Add a debug option to enable/disable console logging
